# Generated by Django 4.1.4 on 2023-02-04 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('articulo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.articulo')),
            ],
        ),
    ]
