# Generated by Django 4.1.5 on 2023-02-11 00:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0004_alter_articulo_autor_delete_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
